### ISSUE TITLE
Preonic doesn't seem to use keymaps folder, probably need to indicate a folder per type

### ISSUE THREAD

**Issue by tdegrunt** [ErgoDox-EZ/reactor#1]

**Comment by ezuk** [comment]
actually, IMHO we can enforce a folder hierarchy. To me that would be the
logical thing to do -- convention over configuration, so to speak.
Keyboards can conform to the structure as needed. Just my opinion. :)

**Comment by tdegrunt** [comment]
@jackhumbert Is there any reason preonic's keymaps are stored in `extended_keymaps`?

**Comment by jackhumbert** [comment]
Sorry - that project hasn't been updated entirely! The whole Preonic project should be similar to the Planck's.

**Comment by tdegrunt** [comment]
@jackhumbert Want me to open an issue on qmk for this?

**Comment by jackhumbert** [comment]
Nah, but it should definitely follow the same form as the Planck - it'll
get changed over once we start getting Preonic PCBs in.

**Comment by tdegrunt** [comment]
Allright, thanks. Closing this.
